# 模型配置
model:
  embedding_dim: 1536  # Qwen1.5的嵌入维度
  hidden_dims: [512, 256]
  num_collections: 6    # 答案集合数量
  dropout_rate: 0.1

# 训练配置
train:
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-5
  epochs: 1024
  save_interval: 2
  eval_interval: 1   # 每多少epoch验证一次
  metric_name: "loss" # 监控指标名称 (loss/accuracy)
  metric_mode: "min"  # 越小越好还是越大越好 (min/max)

# 路径配置
paths:
  data_dir: "./data/processed/embeddings"
  log_dir: "./training/logs"
  checkpoint_dir: "./training/checkpoint_fewer"
  label_dir: "./data/processed/labels"
  trainset_file: 'training/split/train_set.txt'
  valset_file: 'training/split/val_set.txt'
  train_data_dir: './data/train/processed/embeddings'
  val_data_dir: './data/val/processed/embeddings'
  train_label_dir: './data/train/processed/labels'
  val_label_dir: './data/val/processed/labels'

data:
  val_ratio: 0.2    # 验证集比例
  train_ratio: 0.5  # 训练集比例
  num_workers: 4     # 数据加载线程数
  seed: 42           # 随机种子