# 模型配置
model:
  embedding_dim: 1024  # Qwen1.5的嵌入维度
  hidden_dims: [512, 256]
  num_collections: 5    # 答案集合数量

# 训练配置
train:
  batch_size: 32
  learning_rate: 1e-3
  epochs: 10
  save_interval: 2
  eval_interval: 1   # 每多少epoch验证一次
  metric_name: "loss" # 监控指标名称 (loss/accuracy)
  metric_mode: "min"  # 越小越好还是越大越好 (min/max)

# 路径配置
paths:
  data_dir: "./data/processed"
  log_dir: "./training/logs"
  checkpoint_dir: "./training/checkpoint"

data:
  val_ratio: 0.2    # 验证集比例
  num_workers: 4     # 数据加载线程数
  seed: 42           # 随机种子