# 模型配置
model:
  embedding_dim: 1536  # Qwen1.5的嵌入维度
  hidden_dims: [512, 256]
  num_collections: 6    # 答案集合数量
  dropout_rate: 0.1

# 训练配置
train:
  batch_size: 8
  learning_rate: 1e-4
  weight_decay: 1e-5
  epochs: 128
  save_interval: 2
  eval_interval: 1   # 每多少epoch验证一次
  metric_name: "loss" # 监控指标名称 (loss/accuracy)
  metric_mode: "min"  # 越小越好还是越大越好 (min/max)

# 路径配置
paths:
  data_dir: "./data/processed/embeddings"
  log_dir: "./training/logs"
  checkpoint_dir: "./training/checkpoints"
  label_dir: "./data/processed/labels"
  train_data_dir: 'data/v4/ratio_0.8/train/embedding'
  val_data_dir: 'data/v4/ratio_0.8/val/embedding'
  train_label_dir: 'data/v4/ratio_0.8/train/label'
  val_label_dir: 'data/v4/ratio_0.8/val/label'

data:
  train_ratio: 0.8  # 训练集比例
  num_workers: 4     # 数据加载线程数
  seed: 42           # 随机种子